### ISSUE TITLE
add support for i18n

### ISSUE THREAD

**Issue by jmfrancois** [Talend/react-cmf#4]
The goal is to first discuss some point and then provide an implementation in Pull request #23

**Comment by jmfrancois** [comment]
First question : should we enforce the use of i18n in a react-cmf project ?

please answer with 👍 👎

**Comment by jmfrancois** [comment]
https://www.npmjs.com/package/counterpart
https://github.com/i18next/react-i18next

**Comment by talend-glorieux** [comment]
This issue was moved to Talend/ui#26
