### ISSUE TITLE
question: where should I put data from the server to let component read them

### ISSUE THREAD

**Issue by jmfrancois** [Talend/react-cmf#9]
Proposals:

store schema
- cmf
  -- settings
  -- component
  -- collection

each collection fetched from the server should be stored in cmf.collection.MY_COLLECTION_ID

**Comment by acateland** [comment]
Still open with a question, we shoudl rename collections to serverData

**Comment by jmfrancois** [comment]
the naming imply the meaning. We want to fetch data and put them here, so it's a repository of data.

* [ ] remoteData
* [ ] dataset
* [ ] tmp
* [ ] cache
* [ ] serverData

**Comment by talend-glorieux** [comment]
I'm definitely not in favor of `tmp`.
I fear that `dataset` might conflict with the actual datasets we'll have to fetch.
`cache` feels really temporary.

So I would vote for either remoteData or serverData with a slight preference for remoteData.

**Comment by jsomsanith** [comment]
+1 agree with @talend-glorieux 
Plus, `dataset` is too spefic

**Comment by jmfrancois** [comment]
This will be a breaking change. We should do that quickly

**Comment by talend-glorieux** [comment]
This issue was moved to Talend/ui#21
